### ISSUE TITLE
Potential issues with `store` as a prop and shallow test rendering in v6

### ISSUE THREAD

**Issue by markerikson** [reduxjs/react-redux#1161]
I've seen a few different reports related to this topic, so I'm going to open up this issue for discussion.

In React-Redux v6, we removed the ability to pass the store as a prop named `store` directly to connected components.  (See [my post explaining why this change was made](https://blog.isquaredsoftware.com/2018/11/react-redux-history-implementation/#no-more-store-as-a-prop).) 

Generally, the only meaningful use case I knew of for this capability was for unit testing, as some people passed a store directly as a prop instead of wrapping the component in a `<Provider>`.

I've seen some complaints that Enzyme's `shallow()` does not work well with putting a `<Provider>` around a connected component, but I'm not clear on the details of what exactly breaks.

Is it that Enzyme still does not support React's `createContext` correctly?  That rendering `shallow(<Provider store={store}><ConnectedComponent /></Provider>)` does not actually generate any output from `<ConnectedComponent />`?  Something else?

As a related question, what exactly does it mean to "shallow-render a connected component"?  What do tests with this approach look like, particularly in terms of Enzyme API usage and assertions?

I'd appreciate some examples of tests that are having issues, explanations of what specifically is breaking (beyond just "I can't pass the store as a prop any more"), and any further details people can provide related to this issue.

**Comment by dschinkel** [comment]
One of the biggest problems I have is that React and Redux are forcing everyone to use the Context API. And in doing so that requires you to use mount() because you simply can no longer do easy things to components such as shallow. With Redux 6 they shut off the ability to pass in fake stores as props.

I personally don't like using provider in my tests, it's huge bloat. It's been completely necessary the way I code react applications...unless you're writing integration tests. That's the thing, the React team seems to mainly just promote integration testing which is another beef I've had with that "framework". I cannot call this a lib anymore.

What if there are those who don't want to use that for persistence and actually are fine with passing state as props and find that route "simplistic" regardless of the "inconvenience".

The problem I see is that the way React and Redux are moving, they're continually changing the API in a way that undermines the ability to shallow and IMO they don't really care because they would have already noticed that enzyme shallow is breaking due to their major API changes. They're not backward compatible anymore, new react features are literally breaking things and they don't care about isolated tests IMO generally which is my general take on it because if they did they'd already have seen this issue before releasing such major changes to their API.

It's fundamental to be able to shallow components. That's what made react so create in the beginning. VueJS still has that ability in fact it's built right into their testing lib.

I feel like React wants to just stick with Dodds library and kill enzyme honestly. And that's bad for those of us who have built a ton of react code and TDD'd with shallow tests. Regardless of TDD, I'm not saying you have to TDD but those who do just want to be able to continue building these apps. To shut off simple DI like that and to force people down paths that literally kill shallow to me is just not a very good move by React or Redux. The fact is if the React team themselves wrote isolated tests, they would have already seen this pain.

Another TDD'ist I know ranted on not being able to shallow render hooks. So there's no backward compability with React going forward, it's a free for all....especially when they continue to neglect checking for isolated testing.

What if we're not using createContext() and we still want to shallow test components and DI other ways through our isolated tests? Everyone assumes that with new versions of React and Redux people are always going to be using this. That's troublesome.

**Comment by minznerjosh** [comment]
@markerikson FWIW, react actually does plug enzyme in their shallow render docs: https://reactjs.org/docs/shallow-renderer.html

**Comment by dschinkel** [comment]
I'm sorry I sound like a jerk.  It's just a **big** issue for use who have really come to enjoy TDD'ing React and Redux for all this to just change and prevent us from ultimately using shallow and writing isolated tests in very very simple ways.  I guess I feel like this should have already been caught by both teams and I guess I have the feeling that with all the focus on integration tests i see with the React team, that they don't care.  Prove me wrong, I'd love to be proven wrong on that last part.

To be fair, I promised mark a blog post but I just have not had the time.

**Comment by markerikson** [comment]
@dschinkel : I know you have very strong opinions on these issues.  I want to keep those out of this discussion as much as possible.

I'd like to focus _specifically_ on technical aspects of the React-Redux API.  Don't use the word "TDD". Don't complain about how React is changing.  

Tell me what _specific_ technical needs you have, and hopefully we can come up with some solutions that help everybody.

**Comment by dschinkel** [comment]
TDD is part of context here.  Isolated tests is part of context independent of TDD but understanding use cases for either case, and that there are quite a few devs that test via shallow _because of_ TDD's approach to design feedback and evolving a feature is why I mentioned it.  I feel there's a lack of realizing that there is a pretty large group out there who write shallow tests _because of that_.

We can take out TDD from my rants above.  Just replace it with "shallow testing".  Simple.

**Comment by markerikson** [comment]
I know, and I'm saying that phrase is irrelevant to the discussion. I don't care what conceptual approach you're using to write your tests.  I want to know what _technical_ problems you're encountering because of "store-as-prop" being removed, and the other changes in v6, besides the obvious literal "this breaking change broke my code" aspect.

**Comment by ljharb** [comment]
I hope for enzyme to have createContext support soon, but I’d urge you not to drop < 16.3 compat lightly. yes, enzyme is basically the officially endorsed testing solution at the moment, although that could always change if we don’t catch up to React’s feature set quickly enough :-)

I do also hope to have a general solution soon in enzyme that works ergonomically for provider-like components (both createContext Providers, and the incredibly common Provider component pattern, as well as components with lifecycle methods to set up state). Once that exists, it might not be as big of an issue for libraries to make this sort of change.

In other words, ofc do what you like with your library, but here are some thoughts i hope are helpful:

1. enzyme will continue to strive to make it easy and ergonomic to use every React feature, and also/separately, every common community pattern, unrelated to my personal opinion on it (eg: i abhor render props as a bastardization of jsx, but enzyme now has a `.renderProp` API to make working with them easier, and supporting this workflow is a priority whether it’s my favorite or not) This includes the Provider-like support i alluded to above.
1. it can be very user-hostile to aggressively drop support for older platforms (node/browser engines), frameworks (React versions), or patterns (props over context). It would be really pleasant for users of redux if they could continue to use up to date versions of the library without being forced to upgrade node, drop browsers from support, upgrade react, or rewrite their code. It’s also important for redux maintainers to have a pleasant experience maintaining the library, and these concerns often collide. Of course, make the decision you feel is best for your library, but hopefully also for your users :-)

If there’s something enzyme can do that isn’t already being worked on, please do file an issue and I’ll do my best to help find a good solution!

**Comment by markerikson** [comment]
React-Redux v6 already dropped compat for <= 16.3.  We have a minimum peer dependency of 16.4.  16.3 is the minimum for use of `createContext`, and 16.4 brought in the fixes for `getDerivedStateFromProps`.  (We wound up not needing to use `gDSFP` ourselves, but if you're on 16.3, there's no reason not to be on 16.4.)

In general, if you need to stay on React <= 16.3, v5 still works just fine.  

I will say that some of Sebastian's comments in https://github.com/facebook/react/issues/14110 suggest that perhaps the new context API isn't as ideal as it has been described, particularly with the way React-Redux uses it.  Having said that, we still had plenty of good reasons to switch to using it this way in v6, as I described in my blog post, and the removal of "store-as-prop" is a direct technical result of that change.

**Comment by markerikson** [comment]
@dschinkel : I've got free time over the next couple days and can put some attention into this. What I need from you is several actual tests that run under v5, but not under v6, including components. I don't care how "real" the components are, I just need all the actual code for the tests to really run. 

I'm particularly interested in how you are setting up the store, and what you are asserting. 

Ideally, I'd love to have a link to an actual repo that I can just clone , install, and run the tests. Failing that, I'd settle for a complete tests file in a gist. 

I do want to help, especially since there seem to be others dealing with this issue as well, but I need you to give me the resources to investigate so I can figure out options.

**Comment by dschinkel** [comment]
Ok I'll put something up.

**Comment by markerikson** [comment]
Playing around a bit with [a sandbox](https://codesandbox.io/s/xql8pownw) provided by @BTMPL .

Unfortunately, as best as I can tell, `shallow()` simply does not call a `Context.Consumer`'s render callback.  Dan pointed out that [React's shallow renderer is incredibly simplistic](https://github.com/facebook/react/blob/f290138d329aa7aa635d88868705b23372e9f004/packages/react-test-renderer/src/ReactShallowRenderer.js#L112-L190).  It seems like the first blocking issue here is that the shallow renderer at least needs to have some specific support for handling context consumers.

**Comment by minznerjosh** [comment]
@markerikson I opened airbnb/enzyme#1966 to handle that.

**Comment by minznerjosh** [comment]
Though perhaps support should come from react-test-renderer itself in some capacity?

**Comment by markerikson** [comment]
How much of the issue is Enzyme, and how much is the underlying React shallow renderer?

**Comment by minznerjosh** [comment]
It’s sometimes hard to tell. Enzyme does a lot to make shallow rendering behave more like actual react. (Like implementing shouldComponentUpdate, for example.)

The way I’d like to see context supported in enzyme is that you can render a context provider, and then if you dive() the consumer, the render prop will be called with the correct value. The underlying react shallow renderer has no concept of diving, so support for that would have to come from enzyme.

However, I could also imagine a world where the underlying react shallow renderer allows you to render a consumer, and pass in the context value as an option, and it will call the render prop. The aforementioned enzyme feature could be built on top of a shallow renderer feature like this. But it isn’t necessary, as my PR demonstrates.

**Comment by timdorr** [comment]
Potentially dumb idea: what if we added an `unsafe_store` prop to connect? Would it be sufficient for that to only read the state from the store once, or are folks expecting it to subscribe as well? That's what I would expect with shallow rendering, but I figure there are edge cases.

**Comment by markerikson** [comment]
That's roughly where my thoughts were headed - either that, or something like a `overrideMockStoreState` prop.  Something that clearly is not intended for use in an actual app, but would hopefully be sufficient for a test.

**Comment by dschinkel** [comment]
This is why giving you an example takes more than just code, it takes context even explaining how that ties into TDD.  Context meaning testing approach.  When I _test drive_ my code, I do not initially care about testing lifecycle methods or "wiring", to me those are integration tests.  

When enzyme first started out, it didn't even support lifecycle methods.  As developers who wrote more _integration_ tests with shallow, they started to demand shallow to behave more like mount() which to me is borderline a bad decision by enzyme because shallow to me is meant to test the rendered output, not to do full out integration testing like mount is meant for.  If you're designing components, you should strive to decouple logic from your containers anyway and test those independent of your container.

So what I'm saying is, the focus I personally care about is:
a) My existing tests that I wrote for the past 3 years don't break.  I've worked for multiple clients. 
b) The approach I take to TDD (this matters I'm not the only one who does this) React goes like this:

- Shallow render a container

- If that container is wrapped in an HOC, dive() past each HOC because I care about testing the underlying container's output

- Test redux behavior indirectly.  By indirectly this means I send in a fake store which is simply an anonymous method that is a dummy.  I then do _not_ export stuff like mapStateToProps.  I test that after my reducer is hit (lower level tests also test reducers, actions, and other business logic), that state updated the props with expected stub data.  That way if someone screws up mapStateToProps my tests will tell me.  This does not mean I'm testing redux itself, a common misconception that people tend to resort to who don't undrestand testing well just assume when they first glance at example isolated tests.  I'll explain that in my example repo I'll setup

- Once I'm doing TDD'ing the underlying core behavior (not wiring..I don't care about wiring till after the main business logic has been TDD'd for a feature), I actually don't write a lot of integration tests.  Integration tests is a loaded term.  When I say integration tests I mean that I don't test a lot of "wiring" such as "hey did we wire up this button to this function".  You can but I value lower level isolated tests first which is the main issue at stake here

-  I don't care about renderProps.  Consider that many of us don't use it.  Not everyone follows the bandwagon because some of us see drawbacks when you use a lot of nested things together, especially when people nest a bunch of HOCs  and renderProps together and get components that break Single Responsibility so badly, you can't even shallow anymore due to poor design.  My point is, I don't really care about renderProps personally here

Stay tuned I'll hit the example repo creation tonight and with more context and details around the approach.  Again I mention TDD here because most devs are only thinking in integration test mode.  The TDD approach is entirely different then test after and this gives a big part of context here as in "why it's a problem for a lot of devs who TDD" or even "A lot of devs who don't TDD and also don't care about testing the wiring or integration tests first".  I do not follow Dodds recommendation "Mostly integration tests" so keep that in mind as we work through this together.

**Comment by markerikson** [comment]
I really don't care about the justifications for _why_ you write tests a certain way.

I just want to see _how_ you are writing the tests.

**Comment by dschinkel** [comment]
Ugh Mark I get that.  And I'm going to give that to you.  But you also can't just ignore what I'm trying to explain about context.  Testing isn't about just adding tests to some of us.  It's part of an approach.  Context goes with testing and for use cases you're going to have to listen if you want to work together on this.  Stop hating TDD and understand that TDD means there's a lot of context that goes with just showing examples.

**Comment by markerikson** [comment]
Honestly, no, I don't need to know why right now.

I'm not hating on TDD. I'm saying you're spending a lot of time writing long comments about things that don't give me the info I need to help address this issue.

**Comment by dschinkel** [comment]
if you end up doing a prop, keep the name simple. `overrideMockStoreState` is too verbose just make it `mockStore`. I worked on a little tonight, I'll have it done tomorrow morning / early afternoon.

**Comment by dschinkel** [comment]
It'll have to be by tomorrow, got a couple things I want to do before I post this.

**Comment by dschinkel** [comment]
I test my mapStateToProps in a similar way.  I'll have mine up soon.

**Comment by Fandekasp** [comment]
Enzyme has started working on [the ability to dive() consumers](https://github.com/airbnb/enzyme/pull/1966) 10 days ago. Our react-redux v6 upgrade will be completed once they merge this feature and we can update all our tests with store sent as context instead of props

**Comment by markerikson** [comment]
It's looking like I'll probably be snowed in this weekend, so I hope to have time to look into this.  @davesteinberg , thanks for providing an example repo.  @dschinkel , still hoping to see yours as well.

**Comment by dschinkel** [comment]
Will be working more on it this weekend, hopefully get something done and pushed.  I just want to be sure I have different test cases and approaches explained..not just "throw up some code".

**Comment by ignatiusreza** [comment]
Hi guys!

Sorry for jumping in mid-discussion.. I saw that the discussion is centered around the ability to TDD, so I want to bring to light some other potential use of accepting `store` as `props`..

Forms build using `react-redux-form` are connected to the store by default, but the library provide a way to sandbox select form by using `LocalForm` which will peruse passing [store as props](https://github.com/davidkpiano/react-redux-form/blob/v1.16.12/src/components/local-form-component.js#L35) to [inject](https://github.com/davidkpiano/react-redux-form/blob/v1.16.12/src/components/form-component.js#L89) the sandboxed store into the form and [each fields](https://github.com/davidkpiano/react-redux-form/blob/afa9a9680c426fd745d35e4edd360e36d3439557/src/utils/resolve-model.js#L21-L29) under it..

With that said though, I do agree with the recent sentiment that form state should not be stored in redux.. but, it does also means that project which currently are using `react-redux` pre v6 alongside `react-redux-form` won't be able to upgrade without spending substantial amount of effort..

**Comment by BTMPL** [comment]
@ignatiusreza this should be already supported by wrapping the individual form fragment in another Provider that passes another store

**Comment by ignatiusreza** [comment]
@BTMPL that will change the store for ALL decendants of the form fragment, not just the one component being injected.. it won't work in case you want to render non-form related component alongside, which still need to read from the main store..

**Comment by BTMPL** [comment]
You could still create your own context and use the Provider with a custom context, which would allow you to use different store for form and non-form consumers (https://react-redux.js.org/api/provider#props). And yeah, I think we're derailing this issue.

If you have doubts about this functionality, let's open another issue.

**Comment by markerikson** [comment]
I'm okay with broadening the discussion to include other potential uses of "store as prop" as well, and that's the other general use case I was aware of.

**Comment by AnaRobynn** [comment]
@markerikson @dschinkel
In a way yes it sucks when you are unit testing like that. 

In another way you could argue that unit testing this part is too painful, because you have no control over the API (even though we took for granted that the API never really changed over some time). It’s still a risk.

So the fact people are feeling the pain of these tests breaking, because react-redux’s api is breaking is only normal. Are these tests useful? In a way it’s just wiring up container with store, which gets caught 90% of the time in high-level acceptance tests, since they are free from implementation.

Searls’ talk: Don’t mock me, kinda covers this that if you don’t wrap libraries in code you own, their api will bleed through your app, which makes breaking changes hard to deal with.

**Comment by dschinkel** [comment]
I don't want to get into some debate whether passing the prop to a component without a provider is valuable or not.  I'm telling you it is.  I'm telling you I have a ton of tests I've written in the past that are going to break.  I'm telling you myself and many others test this way.  I'd like to keep focus for this Issue on passing store as a prop to Shallow.  I think discussing passing it to the provider is muddying this thread and should be moved to a separate issue.

**Comment by markerikson** [comment]
@dschinkel : I agree and disagree on a couple different parts of that statement.

Overall, the "store as prop to component" API has had two main use cases:

- Testing connected components
- Letting individual components in an app read from a different store than the rest of the tree

Your focus is obviously the testing aspect, which is fine.  But, I need to consider all the use cases from the community.  Given that one API served both use cases previously, ideally I'd like to come up with a solution that handles both use cases going forward.

Also, I think you're misunderstanding the discussion in the prior few comments.  No one's talking about changing how stores are passed to a `<Provider>`.  The issue is that if you try to put a second `<Provider>` around a specific part of your component tree, that whole subtree is now reading from the second store instead of just one individual component.  As @BTMPL mentioned, one _potential_ workaround for that issue is to pass a custom context instance to both the second provider and the one specific component you want to read from that store.


On that note, lemme toss out an idea that had crossed my mind back during 6.0 development work.

What if we brought back the ability to pass a store directly as a prop named `store`, and when that happens, have the connected wrapper component create a unique context instance and render a second provider inside itself, around the actual wrapped component?

The resulting component tree would look roughly like this:

```js
<Parent>
    <Connect(MyComponent) store={secondStore}>
        <UniqueContext.Provider store={secondStore}>
            <UniqueContext.Consumer>
                <MyComponent>
```

I'm not necessarily sure it's a _good_ idea, but it's _an_ idea.

The biggest immediate concern is that I'm not sure if this actually works with Enzyme shallow rendering, especially since it seems that they don't **yet** support context properly.

Thoughts?

**Comment by markerikson** [comment]
Ideally, whatever solution we comes up with works for both `shallow()`, `mount()`, and "real-world" usage.

Technically only `connect()` is a HOC, there's just additional levels of children before the wrapped component.  We're already rendering the consumer.  The current render method looks like this:

```js
      render() {
        const ContextToUse =
          this.props.context &&
          this.props.context.Consumer &&
          isContextConsumer(<this.props.context.Consumer />)
            ? this.props.context
            : Context

        return (
          <ContextToUse.Consumer>
            {this.indirectRenderWrappedComponent}
          </ContextToUse.Consumer>
        )
      }
```

(Which is not quite what I was expecting, since apparently I didn't look carefully enough at the "verify that the `context` prop is a real context" PR.)

Notionally, supporting this might look like:

```js
      render() {
        const {context, store} = this.props

        if(store) {
          const {uniqueContext} = this.state

          return (
              <Provider store={store} context={uniqueContext}>
                <UniqueContext.Consumer>
                  {this.indirectRenderWrappedComponent}
                </UniqueContext.Consumer>
              </Provider>
          )
        }

        let ContextToUse = Context

        if(context &&
          context.Consumer &&
          isContextConsumer(<context.Consumer />)) {
          ContextToUse = context
        }
        
        return (
          <ContextToUse.Consumer>
            {this.indirectRenderWrappedComponent}
          </ContextToUse.Consumer>
        )
      }
```

**Comment by just-boris** [comment]
> Also no idea why @just-boris thumbed down my last reply. Please explain

A week ago you were going to provide a demo showing your use-case with shallow testing. That was the main reason for me to subscribe for this thread. The time has passed, still, no demo from you, and the discussion is making rounds.

> I don't want to get into some debate whether passing the store as a prop to a component without a provider is valuable or not. I'm telling you it is.

A code example would weigh much more than any verbal discussions.

**Comment by dschinkel** [comment]
I am on vacation with my family right now, it takes time, we're all busy.  It's going to take time and there is no reason I can't respond to others such as @AnaRobynn.

Be patient.

**Comment by dschinkel** [comment]
> As for calling dive(), I know at some point I saw someone write a function that repeatedly dive()s in a loop until it finds the correct component

@markerikson Are you referring to a recursive dive?  I'm not for that because it ignores design feedback.  If you just ignore all the HOCs you're not getting pressure to simplify your design which is a big reason we use shallow.  @ljharb and I discussed this and that we should never add a recursive dive to shallow.

**Comment by AnaRobynn** [comment]
I think we have to make a difference here between two things:
a) redux v6 preventing us from using shallow
b) redux v6 is breaking the shallow tests

Personally if a) is the reason for the discussion, I think that’s perfectly valid.

If the reason is b) without a) then your complaint about removing the store prop is in essense: “I want to upgrade a library to a breaking change and expect no tests to break”.

That to me is less of a valid argument, because you need to update your tests to use this new API for them to work.

And honestly it’s not a fault of react-redux, but rather the impact on react-redux, because of the changes in React.

**Comment by dschinkel** [comment]
I've stated from the beginning both are valid concerns.  APIs should be very careful when they "take stuff out".  That goes with any API.  You can't just wave off the fact that for the past 3-4 years people have used shallow with store props.  I disagree.  You have to consider your API and changes to them are important.  React has always considered that up till now.  

I don't care what you feel are valid, I'm telling you what's affecting us all.

**Comment by thehig** [comment]
I've whipped up a codesandbox example that demonstrates
- React, Redux and Reselect set up to render a simple page
- A contrived set of enzyme tests that will *hopefully* illustrate the problem

https://codesandbox.io/s/vvp40lqky0

**Comment by willdurand** [comment]
Hi there, we use a testing pattern on a large test suite and we cannot upgrade to react-redux 6 because of the inability to inject `store` as a prop (with Enzyme and `shallow()`).

Since you asked for concrete examples, my colleague @kumar303 described our testing pattern here: https://hacks.mozilla.org/2018/04/testing-strategies-for-react-and-redux/ (with a helper function called `shallowUntilTarget()`).

We are working on improving our helper so that it becomes compatible with react-redux 6 hopefully.

**Comment by dschinkel** [comment]
My way of testing is similar to @kumar303 do you still need more examples @markerikson ?  Seems like we have a pretty good amount already here as far as examples.

**Comment by kumar303** [comment]
> Enzyme's `shallow()` does not work well with putting a `<Provider>` around a connected component, but I'm not clear on the details of what exactly breaks.
> 
> Is it that Enzyme still does not support React's `createContext` correctly?

Yes, exactly 🤑 It's been mentioned before in this thread but I didn't see a link to the tracking issue https://github.com/airbnb/enzyme/issues/1958#issuecomment-450614916 (in case folks want to subscribe).

Maybe when that's fixed everything will work but until then it doesn't seem possible to do this type of shallow rendering with `react-redux` 6.0.0 & Enzyme (I couldn't find a way).

**Comment by dschinkel** [comment]
It's not possible and in fact I prefer not to use provider around shallow anyway.  It keeps my test setup simple and keeps my stub data scoped to each test.  I think passing in a store prop directly to the component keeps stuff way simpler anyway.

**Comment by markerikson** [comment]
This issue has been partially superseded by the roadmap I just laid out in #1177 .

Key point: we're going to switch `connect` back to using direct subscriptions internally, which means we can also bring back the use of `store` as a prop, same as we had up through v5.

I'll leave this open for now, but basically this will get resolved when we actually figure out what the right internal re-mplementation of subscription logic is.

**Comment by EzraSingh** [comment]
@dschinkel may I suggest using named exports to expose connected components to mitigate testing connected components, below is an example pattern.

```javascript
// ...
export { Foo as FooComponent }; // <- For component testing
export default connect(mapStateToProps, mapDispatchToProps)(Foo);
```

 This would simplify mocking the Redux mappers along with any other props. Here is a potential testing pattern:

```javascript
import { FooComponent } from 'src/components/Foo';

//...

const props = { someReducer: jest.fn(), someProp: true  };
const wrapper = shallow(<FooComponent {...props} />);
```

**Comment by ljharb** [comment]
@EzraSingh that's an antipattern; if a component is never used in production unwrapped, it should never be tested unwrapped.

**Comment by EzraSingh** [comment]
@ljharb however, if your connected component is responsible for dispatching an action on click or on mounting it would be pragmatic to want to test the functionality of such a component. One could argue that by connecting the component you are using it *unwrapped* because it may be responsible for some dynamic interactions contrary to its container usage.

```javascript
class Logout extends Component{
    static propTypes = { 
        logout: PropTypes.func.isRequired,
        isLoggedIn: PropTypes.bool.isRequired
    }
    componentDidMount(){
        this.props.logout()
    }
    render(){
        return this.props.isLoggedIn ? "Logging out" : <Redirect to="/">
    }
}

// ...

export default connect(mapStateToProps, mapDispatchToProps)(Logout)
```

**Comment by jamesg1** [comment]
That pattern makes sense if you want to test your component in isolation removing redux dependencies. If you decided to move away from redux your tests would work as its just a normal component. You'd need to make sure you would cover the scenarios from which the props would come from in your store.

**Comment by ljharb** [comment]
@jamesg1 i'm suggesting that you shouldn't *want* to test something in isolation that's never possible to use in production in isolation. If you decide to move away from redux, you'd have to make lots of changes, so it's unreasonable to expect that tests for components utilizing it won't also require changes.

**Comment by AnaRobynn** [comment]
That’s why I think components should do one thing and one thing great. Components fetching data/managing state shouldn’t care rendering elements. 
So you’d have your state wrapping component, which gets it’s values from local state, hooks, redux whatever. Exporting that component without the way it gets data is useless, because the only thing it’s responsible for it gathering the data. Exporting unconnected components kinda feel the same, just doesn’t makes sense.

But that’s not at all relevant to the discussion I think?

**Comment by markerikson** [comment]
Nope, not at all.

The point of the original issue is:

- We had an API in version <=5 (`store` as prop) that folks relied on for two specific use cases (testing and isolating components in a larger tree)
- We offered a suggested approach for the "isolated component" use case, but there were testing-related usages we weren't aware would become problematic
- Figuring out what approach, if any, would resolve those concerns

Per [my earlier comment](https://github.com/reduxjs/react-redux/issues/1161#issuecomment-460022310), this will likely be resolved by an internal architectural change that will allow us to re-add the `store` as prop API, and thus solve those use cases.

Discussion of why some people prefer to test one way or another, or what the "right" approach is for testing things, is irrelevant to this issue.

**Comment by NunoCardoso** [comment]
> Nope, not at all.
> 
> The point of the original issue is:
> 
> * We had an API in version <=5 (`store` as prop) that folks relied on for two specific use cases (testing and isolating components in a larger tree)
> * We offered a suggested approach for the "isolated component" use case, but there were testing-related usages we weren't aware would become problematic
> * Figuring out what approach, if any, would resolve those concerns
> 
> Per [my earlier comment](https://github.com/reduxjs/react-redux/issues/1161#issuecomment-460022310), this will likely be resolved by an internal architectural change that will allow us to re-add the `store` as prop API, and thus solve those use cases.
> 
> Discussion of why some people prefer to test one way or another, or what the "right" approach is for testing things, is irrelevant to this issue.

Thank you for this clear comment. I was puzzled on how all the examples of store mocking with jest I found around were not working properly. Downgraded to react-redux 5.1.1 and all works fine.

I hope anyone who is looking for the same answers will find your post. I am a little skeptic over adding a functionality on prod code only for the sake of testing, but in this case, I think the pros beat the cons.

**Comment by hjhimanshu01** [comment]
@markerikson  , any updates on how to pass store to components while using shallow for testing ?

Sample issue : 
```wrapper = shallow(
      <Provider store={store}>
      <Component />
      </Provider>
    );
```
store configured via  'redux-mock-store'.

**Comment by markerikson** [comment]
@hjhimanshu01 : this _should_ be fixed in the v7 alpha.  Try adding it as an alias:

`yarn add react-redux@npm:@acemarke/react-redux@next`

Also note that you need `react@^16.8.2` for this.

**Comment by hjhimanshu01** [comment]
@markerikson , I'm sorry , I didn't got what you explained , please could you elaborate a little?

**Comment by dschinkel** [comment]
>Thank you for this clear comment. I was puzzled on how all the examples of store mocking with jest

And this is why I don't use mocking frameworks :).  I don't need a mocking framework to mock the store.  I just pass dummies to plug holes for the store as a prop.

**Comment by AnaRobynn** [comment]
@dschinkel
I agree with having to use elaborate mocking framework is a sign, mock should be straightforward and used in very particular cases.

I don’t agree with the statements that when you test your containers, that they are not coupled to redux. They are 100% coupled to redux, that’s just nature of HOCs.

I also don’t agree that your container tests don’t know anything about redux in test, because they are aware, since you need to pass down a store prop. Do implicitly you have a dependency on Redux.

But again, I think this is just the nature of the redux connected components/tests. They are coupled and it’s ok they are aware, since it’s small integration test.

**Comment by markerikson** [comment]
*sigh*

Folks, [as I already said](https://github.com/reduxjs/react-redux/issues/1161#issuecomment-463850841): please refrain from continuing discussions about various testing methodologies in this thread, or I'm going to have to lock it.

The [version 7 alpha](https://github.com/reduxjs/react-redux/issues/1177#issuecomment-472262580) re-adds the ability to pass `store` as a prop to connected components.  Please try that out and see if it resolves your issues.  The latest version is `@acemarke/react-redux@7.0.0-alpha.5`, which is tagged as `next`.

The easiest way to try it is to add it as an alias for `react-redux` when installing it:

`yarn add react-redux@npm:@acemarke/react-redux@next`

Note that since v7 uses hooks internally, you'll need to have at least React 16.8.2, and you'll probably need to use React's new `act()` test API to wrap any bits of your test that might update the components.

**Comment by hjhimanshu01** [comment]
@dschinkel , actually , that code snippet was written by someone else .

Here's the snippet 
```
const container = wrapper.dive({ context: { store } }).dive();

    expect(
      container.find('AnotherComponent').first().props().propValue
    ).to.eql(expectedPropValue);
```

I do think it is integration testing usedd here , but can't say exactly.

**Comment by markerikson** [comment]
This should be resolved now that [v7 is out](https://github.com/reduxjs/react-redux/releases/tag/v7.0.1) and you can pass `store` as a prop again.

**Comment by shiraze** [comment]
I'm still seeing this issue in v7.
I'm using React 16.8.6, Enzyme 3.8.0.
Issue didn't exist with react-redux 5.1.0, but updating to 7.0.3 causes unit tests that rely on store prop to now fail.

Example unit test that fails:
`import React from "react";

import MainPage from "./mainPage";

import Enzyme from "enzyme";
import Adapter from "enzyme-adapter-react-16";
import { createShallow } from "@material-ui/core/test-utils";

import configureMockStore from "redux-mock-store";
import thunk from "redux-thunk";
const middlewares = [thunk];
const mockStore = configureMockStore(middlewares);

Enzyme.configure({ adapter: new Adapter() });

jest.mock("./dataFormContainer", () => "MockedDataFormContainer");
jest.mock("./resultsList", () => "MockedResultsList");
jest.mock("../style/mainPage.css", () => ({
  withStyles: component => component,
}));

describe("MainPage renders correct subcomponent", () => {
  let wrapper, store, shallow;

  beforeEach(() => {
    shallow = createShallow({ dive: true });
  });

  it("renders a DataFormContainer when activeForm is set", () => {
    store = mockStore({
      mainPage: {
        activeForm: {
          form: "myform",
          desc: "form title",
        },
        connection: "href/entity",
        query: "searchItem",
      },
      logon: {},
    });

    wrapper = shallow(<MainPage store={store} />).shallow();

    expect(wrapper.find("MockedDataFormContainer")).toHaveLength(1);
    expect(wrapper.find("MockedResultsList")).toHaveLength(0);

    expect(wrapper.find("MockedDataFormContainer").prop("title")).toBe(
      "form title"
    );
  });
});
`

I get this error thrown when attempting to run test:
`    TypeError: ShallowWrapper::dive() can only be called on components

      40 |     });
      41 |
    > 42 |     wrapper = shallow(<MainPage store={store} />).shallow();
         |               ^
      43 |
      44 |     expect(wrapper.find("MockedDataFormContainer")).toHaveLength(1);
      45 |     expect(wrapper.find("MockedResultsList")).toHaveLength(0);

      at ShallowWrapper.<anonymous> (node_modules/enzyme/build/ShallowWrapper.js:2057:19)
      at ShallowWrapper.single (node_modules/enzyme/build/ShallowWrapper.js:1960:25)
      at ShallowWrapper.dive (node_modules/enzyme/build/ShallowWrapper.js:2051:21)
      at shallowWithContext (node_modules/@material-ui/core/test-utils/createShallow.js:37:22)`

I'm using an enhanced shallow provided by the Material-UI team (https://material-ui.com/guides/testing/#createshallow-options-shallow), but in effect I'm just doing:
`wrapper = shallow(<MainPage store={store} />).dive();` if I were to use shallow from enzyme.

The problem appears to be that the result of shallow() is now `<ConnectFunction store={{...}} classes={{...}} />` whereas before it used to `<Connect(MainPage) store={{...}} classes={{...}} />`

**Comment by markerikson** [comment]
@shiraze : two possible guesses for what's happening:

- `connect` now uses `React.memo()` to wrap our own component, so there's technically two levels of wrapping going on.  That may mean you might have to `dive()` twice or something
- it's also possible that Enzyme doesn't know how to deal well with `React.memo()`-wrapped components

**Comment by ljharb** [comment]
This should improve in the next release of enzyme.

**Comment by shiraze** [comment]
Thanks @markerikson and @ljharb . I'm actually thinking of changing our coding style so all our components are tested independently of HOCs like connect(), as described here: https://redux.js.org/recipes/writing-tests#connected-components
I'll then separately test their wrapped behaviour by using <Provider>

This should make tests easier, and also lead to component development decoupled from HOCs

**Comment by bruno-edo** [comment]
@ljharb Currently I'm using Enzyme's v 3.10.0 and am experiencing the issue @shiraze described. Any updates on when Enzyme will be able to shallow render components connected to Redux v7?

**Comment by timdorr** [comment]
It may be dependant on airbnb/enzyme#2011

**Comment by ljharb** [comment]
@bruno-edo please file an issue on enzyme itself for that; it should work with latest enzyme, the latest react 16 adapter, and the latest react-test-renderer.

**Comment by bruno-edo** [comment]
@ljharb I was using both the latest enzyme and adapter versions, but I was unaware that `react-test-renderer` was also required. Would you perhaps be able to post a link with an example on the correct way to use Enzyme to shallow render a connected component (I want to avoid posting an unnecessary issue report)?

Also, the project I'm trying to use Enzyme on is a React Native project, so maybe that is part of the issue?

**Comment by ljharb** [comment]
@bruno-edo it's a direct dependency of the react 16 adapter, but if you have a lockfile you'll need to ensure that's updated also to match your react version.

Certainly there'll be issues with RN, since the current adapters are for react-dom, not react-native. Track https://github.com/airbnb/enzyme/issues/1436 for that.

Let's please, though, all move enzyme discussion to the enzyme repo and stop bothering the redux maintainers with off topic discussion :-)
