### ISSUE TITLE
Unable to resolve "./utils/batch" from "node_modules/react-redux/lib/index.js" react-redux 6.0.0

### ISSUE THREAD

**Issue by Divine1** [reduxjs/react-redux#1241]
i just downloaded `react-redux 6.0.0`

i'm getting below error
`Unable to resolve "./utils/batch" from "node_modules/react-redux/lib/index.js"`

i checked in my `node_modules` under `react-redux` i don't find any `./utils/batch`.

in another setup i use `react-redux 7.0.1` and i can find `./utils/batch` in this version.

why isn't `./utils/batch` not present in `react-redux 6.0.0`?

**Comment by markerikson** [comment]
Because [we only added it in v7](https://github.com/reduxjs/react-redux/releases/tag/v7.0.1).

It sounds like you've got a mismatched set of files in your `node_modules`.  I'd suggest clearing out the `node_modules` folder in that app and reinstalling things.

**Comment by Divine1** [comment]
@markerikson thank you

this config resolved the problem 
```
react : 16.8.6
react-redux : 6.0.0
redux : 4.0.1
```

when i use `react-redux : 7.0.2` i get below error **but** only on `react-native expo`

`_react.default.memo is not a function | wrapWithConnect issues`

my problem solved is solved for now

```

"dependencies": {
        "@expo/vector-icons": "6.3.1",
        "axios": "^0.18.0",
        "crypto-js": "^3.1.9-1",
        "expo": "^32.0.0",
        "gl-react": "^3.15.0",
        "gl-react-expo": "https://firebasestorage.googleapis.com/v0/b/react-native-ui-kits.appspot.com/o/npm%2Fgl-react-expo-3.16.4.tgz?alt=media&token=57526b5b-96a3-493c-a9d2-288bb5409648",
        "jest-junit-reporter": "^1.1.0",
        "lodash": "^4.17.4",
        "moment": "^2.18.1",
        "react": "^16.8.6",
        "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
        "react-native-datepicker": "1.6.0",
        "react-native-keyboard-spacer": "^0.4.1",
        "react-native-maps-super-cluster": "^1.3.1",
        "react-navigation": "^3.0.9",
        "react-redux": "^6.0.0",
        "redux": "^4.0.1"
    }

```

**Comment by zhuxinhuan** [comment]
"react": `"16.8.6",`
    "react-native": "0.57.8",
"react-redux": "6.0.0",
    "redux-thunk": "^2.3.0",
    "redux": "^4.0.1"


when I start the App ,it still get the error :::  "Unable to resolve "./utils/batch" from "node_modules/react-redux/lib/index.js"
I  tried to clearing out the node_modules folder in that app and reinstalling things. but it doesnt works for me
@markerikson
